### ISSUE TITLE
Unified a7 object causes crash on Pi1 when preloading library

### ISSUE THREAD

**Issue by samnazarko** [bavison/arm-mem#3]
Hi,

After e6c03fd682479b7c3c7ef3d9bcf685342a5efdab and adding this to /etc/ld.so.preload I get a segmentation fault at boot on Pi1 with Raspbian. Have not had this issue with earlier versions of your library. My init instantly segfaults, and as pid1 dies, kernel oops! Removing the preload line brought me back up. 

Here is output of readelf -A on the shared object generated under Raspbian Jessie using GCC 4.9.1 as the compiler:

File Attributes
  Tag_CPU_name: "6"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6

For now I am tempted to use your earlier build which had a separate lib for a7 as we package this library twice anyway (once for rbp1 and once for rbp2), but it's good to report this kind of thing.

gdb is not helpful, because I am not sure set env LD_PRELOAD was working properly

**Comment by bavison** [comment]
Thanks for the report. Eben expressed a preference for a single unified library to me, so I'd like to avoid going back if I can. Unfortunately I'm having difficulty reproducing your problem, though.

Could you try the first version that used indirect functions (c14fb1c) and say if you see the same thing? This would help narrow down whether it's the general runtime CPU detection concept, or the specific method that I'm using, that's causing the issue.

At first I thought maybe the test was failing due to a bad interaction with the CPU's unaligned load support. But I've checked the ARM ARM and in the definition of BranchWritePC (which is what the SUB instruction is defined to do on ARMv6) it's quite unambiguous that the bottom two bits are ignored. Just in case there's a silicon bug, I've also tried out the instruction with the unaligned load state set all three ways (generating aborts, ARMv5 style and ARMv7 style) and I'd not seeing any ill effects.

**Comment by bavison** [comment]
@samnazarko Which version of glibc do you have installed? I did experience some difficulties with the initial test programs I used to try out indirect functions until I upgraded to glibc 2.19. However, they seemed to be functional as long as they were only called within the libarmmem library (rather than in main()) if I went back to glibc 2.13; however it's possible that I only ever tested a limited number of binaries by manually setting LD_PRELOAD rather than by changing /etc/ld.so.preload. I just tried that on an install with glibc 2.13 and it's failing to finish initialising X (and I also can't SSH into it to check what's happening…)

**Comment by samnazarko** [comment]
Ben,

Thanks for getting back to me. For now, for Pi1 I've reverted to just using cd2c8f9202137c79f7afb77ecb87e713a0800d3c, but it would be good to get this fixed. 

My version of glibc: 

`dpkg -l | grep libc6
ii  libc6:armhf                          2.19-15                   armhf        GNU C Library: Shared libraries`

I built this image via debootstrap just yesterday, so I'm up to date on packages. 

I have built c14fb1ce601989559df9c53203994386bbcb1e40 and I am still having this problem. 

I am concerned you are using procfs to check hardware capabilities. I notice my init (systemd) is segfaulting, as is even a simple command like /bin/echo. However if I remove the preload line and LD_PRELOAD=/usr/lib/libarmmem.so /bin/echo hi after boot, the library works. The init system must bring up the filesystem mounts, but ld.so.preload is going to be executed already. 

I created a /super_early_init which mounts proc before calling systemd, then re-echos the /usr/lib/libarmmem.so into /etc/ld.so.preload. Here it is:

```
#!/bin/sh
mount -t proc proc /proc
mount -o remount,rw / # We are ro in early stages and usually systemd does this!
echo "/usr/lib/libarmmem.so" >> /etc/ld.so.preload
exec /sbin/init $* 
```

This still doesn't fix the boot. I've verified /proc is indeed mounted. 

Normally, /proc is _not_ mounted by the time systemd is executed (we don't use a ramdisk and therefore nothing else mounts anything). I could strace it to prove it but that now means that libc6 will be preloading libarmmem and the hw capabilities check will not get a handle on /proc/self/auxv. Does your implementation handle a lack of procfs gracefully? 

Further, if you would like a filesystem image where this issue occurs, please send me an email (I emailed you at your RISC OS email, so you can get it from there). I can replicate this 100% of the time on the following Pi:

processor   : 0
model name  : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS    : 2.42
Features    : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xb76
CPU revision    : 7

Hardware    : BCM2708
Revision    : 000d
Serial      : 0000000030dd8637

I have emailed you my .so which is giving me problems as well.

Please let me know if you need any more information

**Comment by bavison** [comment]
I'm now pretty certain the problem is something to do with indirect function support (presumably something in ld-linux-armhf.so). I can generate a segfault, with glibc 2.19 installed, as follows:
- Comment out /etc/ld.so.preload
- Reboot, to be sure there's nothing lingering
- LD_PRELOAD=path/to/libarmmem.so /usr/bin/man

This happens even if libarmmem is edited so that the indirect functions unconditionally return a pointer to the ARMv6 implementation. There appears to be something special about the "man" binary, as other executables operate just fine in its place.

I appreciate the discussion of procfs. You may notice that in later revisions, I removed use of procfs in favour of a chunk of magic assembly which avoided the use of any syscalls at all because I was worried about the side effects of doing so. Although I did check for errors from procfs, there were other things I was concerned about (such as the fact that calling memcpy could cause errno to be set). I hadn't considered the possibility that the dynamic linker might be required before procfs was initialised, but it just further reinforces that this was a bad idea.

Now if I could just figure out what was going wrong with the simplified test case - it basically seems to end up branching into the middle of nowhere...

**Comment by samnazarko** [comment]
Hi Ben,

> There appears to be something special about the "man" binary, as other executables operate just fine in its place.

Possibly. I had similar thinking with some binaries first, but quickly noticed that sometimes they segfaulted (i.e /bin/ls), and sometimes they did not. I can't get consistency here with the exception of systemd.

> I appreciate the discussion of procfs. You may notice that in later revisions, I removed use of procfs in favour of a chunk of magic assembly which avoided the use of any syscalls at all because I was worried about the side effects of doing so

Indeed, I did notice it, I just wanted to make clear the issues around procfs if the indirect function method was used at that commit instead. 

Not to digress, but building for Pi2 master is giving me a problem too:

gcc -c -o architecture.o architecture.S
gcc -std=gnu99 -O2 -c -o arm-mem.o arm-mem.c
gcc -c -o memcmp.o memcmp.S
gcc -c -o memcpymove.o memcpymove.S
gcc -c -o memcpymove-a7.o memcpymove-a7.S
gcc -c -o memset.o memset.S
gcc -shared -o libarmmem.so architecture.o arm-mem.o memcmp.o memcpymove.o memcpymove-a7.o memset.o
/usr/bin/ld: arm-mem.o: relocation R_ARM_THM_MOVW_ABS_NC against `memcpy_cortexa7' can not be used when making a shared object; recompile with -fPIC
arm-mem.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:13: recipe for target 'libarmmem.so' failed

This base is Debian Jessie (armv7) from debootstrap. Please do let me know if I can help you with any information that might help you resolve this. 

S

**Comment by samnazarko** [comment]
gcc -shared -fPIC -o libarmmem.so architecture.o arm-mem.o memcmp.o memcpymove.o memcpymove-a7.o memset.o
/usr/bin/ld: arm-mem.o: relocation R_ARM_THM_MOVW_ABS_NC against `memcpy_cortexa7' can not be used when making a shared object; recompile with -fPIC

still presents after

libarmmem.so: $(OBJS)
        $(CROSS_COMPILE)gcc -shared -fPIC -o $@ $^

**Comment by bavison** [comment]
I'm probably not going to be able to get to the bottom of the indirect function weirdness - will try to find out how to raise a fault against glibc and then revert back to separate builds of libarmmem.

> R_ARM_THM_MOVW_ABS_NC

I'm not sure what's going on there. Apart from the obvious fact that it built for me, there are two reasons why that shouldn't be happening:
- As far as I can tell, that's a Thumb-2 relocation. You can't build libarmmem as Thumb-2 at the moment even if you wanted to (mostly due to lack of IT directives) and the .arm directives at the top of each source file force it to be assembled as ARM.
- MOVW is only used in one source line, and the value it encodes is an absolute value - it shouldn't require relocation

If I do
objdump -r memcpymove-a7.o
then the only relocations listed are R_ARM_REL32. What do you see?

**Comment by samnazarko** [comment]
Ben,

RELOCATION RECORDS FOR [.eh_frame]:
OFFSET   TYPE              VALUE 
0000001c R_ARM_REL32       .text
0000003c R_ARM_REL32       .text

is all I see.

Upstream Debian toolchain gives me:

gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by samnazarko** [comment]
Can no longer replicate this issue. 

root@osmc:/home/osmc/out/usr/lib# LD_PRELOAD=$(pwd)/libarmmem.so apt-get update
Hit http://ftp.debian.org jessie InRelease  
Get:1 http://ftp.debian.org jessie-updates InRelease [126 kB]
Get:2 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:3 http://apt.osmc.tv jessie InRelease [3,684 B]
Hit http://ftp.debian.org jessie/main armhf Packages 
Get:4 http://security.debian.org jessie/updates/main armhf Packages [68.4 kB]   

/proc/self/maps looks good from a bash shell and I have no issues.

76f0e000-76f0f000 rw-p 00001000 b3:02 265371      /usr/lib/libarmmem.so

**Comment by bavison** [comment]
Just to clarify, is this with the head version of libarmmem? I have dropped back to providing separate ARMv6 and ARMv7 versions of the library at head at the moment (so you might want to check you're using the correct version). The bug with indirect functions has been raised against glibc but there hasn't been any activity from them yet.

**Comment by samnazarko** [comment]
Thanks for this, I was packaging the wrong version of the library.

Nonetheless, after ensuring the appropriate a7 library was used, I can no longer replicate this issue on a Pi2, so the issue is now resolved.

Thanks

S
